version: '3.8'

services:
  catalogolivros:
    build:
      context: ./1_catalogoLivros
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    networks:
      - app-network
    environment:
      - PWD=password

  integracaoservico:
    build:
      context: ./2_integracaoServico
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    networks:
      - app-network
    environment:
      - PWD=password
      - PWD_EMAIL= SENHA_EMAIL
      - CHAVE_API= CHAVE_API

  seguranca:
    build:
      context: ./3_seguranca
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
